### ISSUE TITLE
Background issues.

### ISSUE THREAD

**Issue by Kakarifers** [CorbsEditor/Dream-Frame#1]
Really loving the theme, but I'm unsure if the background is supposed to scale is it is, or if it is intended for it to scale to completely cover the Discord window. Is it possible to have it where it will fill any and all space with the background image of your choosing?

The background is as such: https://i.imgur.com/3XFxvBf.jpg.  It would be nice to remove the black space entirely if possible.

**Comment by CorbsEditor** [comment]
No, but a new scaling option has already been worked on, but has no yet been released.

**Comment by Kakarifers** [comment]
Ah, any ETA on when that scaling option will potentially be released?

**Comment by CorbsEditor** [comment]
I don't really schedule my releases. But at least this week.

**Comment by Kakarifers** [comment]
Gotcha. Much appreciate. Keep up the awesome work.

**Comment by Kakarifers** [comment]
Like so? https://i.imgur.com/Ef3leAJ.png
If so, changing the number isn't doing anything for me.

**Comment by CorbsEditor** [comment]
The update takes time to get out to everyone. Wait a few hours or wait until tomorrow.
