### ISSUE TITLE
Home icon.

### ISSUE THREAD

**Issue by Deemolition** [CorbsEditor/Dream-Frame#2]
**Describing the issue**
When I edit the file with Notepad++, I try changing the home icon, yet nothing happens. I've tried many links from different websites, yet it remains the same. If you could give any insight, I would be very appreciative. 

**Screenshot**
Show an image of the issue so I can better understand. I am visual learner.
![image](https://user-images.githubusercontent.com/47147201/51912446-fcd07880-2399-11e9-91f5-1b916b95b338.png)
![image](https://user-images.githubusercontent.com/47147201/51912454-035ef000-239a-11e9-929b-5489eb50afa7.png)

**Comment by CorbsEditor** [comment]
This will be working in v2.4
Please wait while as v2.4 is being worked. 
![Preview of Home Icon in v2.4](https://imgur.com/67p7yMc.png)

**Comment by CorbsEditor** [comment]
There is beta: https://github.com/CorbsEditor/Dream-Frame-Beta

**Comment by Deemolition** [comment]
Ah, thank you very much for the info.

**Comment by CorbsEditor** [comment]
Update: v2.4 is coming soon! 
This should be it!
